### ISSUE TITLE
Fractal Community: Dumpster Needed for Gilbert Ramirez Park

### ISSUE THREAD

**Issue by ajroberts0417** [ajroberts0417/NeighborhoodNYC#2]
**Is your feature request related to a problem? Please describe.**
There are always large bags of trash just sitting next to Gilbert Ramirez Park -- can we create or acquire some sort of trash container for them. Y'know... like a dumpster?

**Pictures and screenshots**
Pile of fly-ridden trash at park could use a garbage can
![20220628_193938](https://user-images.githubusercontent.com/25114792/178315451-4097047e-a0de-4912-8807-490d9e33a2ba.jpg)

**Describe the solution you'd like**
A dumpster could be placed in or near the edge of the park for trash?

**Describe alternatives you've considered**
Maybe like a cute little wooden structure with some trees around it labelled "trash"? It might be cuter than a dumpster, tbh

**Tasks**
Include specific tasks in the order they need to be done in.
- [ ] Figure out which city department is responsible for this park
- [ ] Give them a call and ask what's up?
- [ ] ???
- [ ] Build a little trash container ourselves if nobody else will do anything
